### Library

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
#import seaborn as sns
import pickle
import datacompy
import os, sys
import numpy as np
import re
import ast
import gower
from pathlib import Path

# narzedzia
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    cross_val_predict,
    learning_curve,
    RepeatedStratifiedKFold,
    GridSearchCV,
)
from collections import Counter
from sklearn.metrics import classification_report, confusion_matrix, silhouette_score, accuracy_score, pairwise_distances
from sklearn.metrics.pairwise import cosine_similarity
from sklearn import tree
from sklearn.tree import plot_tree
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from scipy import stats
from scipy.stats import chi2_contingency
from scipy.spatial import distance
from joblib import dump, load

# modele
from xgboost import XGBClassifier, XGBRFClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# methods
from imblearn.under_sampling import ClusterCentroids, NearMiss
from scipy.optimize import differential_evolution
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN, HDBSCAN
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor, KNeighborsClassifier, NearestNeighbors
from sklearn.inspection import permutation_importance
from scipy.spatial.distance import euclidean
from imblearn.over_sampling import SMOTE, BorderlineSMOTE
#from ctgan import CTGAN

C:\Users\mateu\AppData\Local\Temp\ipykernel_26388\1510252685.py:5: UserWarning: SparkPandasCompare currently only supports Numpy < 2.Please note that the SparkPandasCompare functionality will not work and currently is not supported.
  import datacompy

### Read datasets after preprocessed

In [2]:
#oversampling data
original_df = pd.read_csv("D:\\ml\\undersampling_data\\data\\ssh\\encoded_normalized\\original_data_normalized.csv")
mix_df = pd.read_csv("D:\\ml\\undersampling_data\\data\\ssh\\encoded_normalized\\mix_data_normalized.csv")
smote_df = pd.read_csv("D:\\ml\\undersampling_data\\data\\ssh\\encoded_normalized\\smote_data_normalized.csv") 
gan_df = pd.read_csv("D:\\ml\\undersampling_data\\data\\ssh\\encoded_normalized\\gan_data_normalized.csv")
borderline_df = pd.read_csv("D:\\ml\\undersampling_data\\data\\ssh\\encoded_normalized\\borderline_data_normalized.csv")

X_test = pd.read_csv("D:\\ml\\undersampling_data\\data\\ssh\\test\\X_test_norm.csv")

In [3]:
#Before undersampling
print(original_df["target"].value_counts())
count1=original_df["target"].value_counts().sum()
count2=abs((original_df['target']==0).sum() - (original_df['target']==1).sum())
print(f"Before undersampling: {count2}")
print(f"After number of samples: {count1+count2}")

target
0.0    151
1.0     46
Name: count, dtype: int64
Before undersampling: 105
After number of samples: 302

In [4]:
#Sum up all df 
sum_all_data = pd.concat([smote_df, gan_df, borderline_df, original_df], axis=0, ignore_index=True)

#Split data
X_mix, y_mix = mix_df.drop(columns=["target", "source"]), mix_df["target"]
X_smote, y_smote = smote_df.drop(columns=["target", "source"]), smote_df["target"]
X_GAN, y_GAN = gan_df.drop(columns=["target", "source"]), gan_df["target"]
X_borderline, y_borderline = borderline_df.drop(columns=["target", "source"]), borderline_df["target"]

#Dictionary
data = {}
data["mix"] = (X_mix, y_mix)
data["smote"] = (X_smote, y_smote)
data["GAN"] = (X_GAN, y_GAN)
data["borderline"] = (X_borderline, y_borderline)

compare = {}
compare["mix"] = mix_df
compare["smote"] = smote_df
compare["GAN"] = gan_df
compare["borderline"] = borderline_df

### Undersampling df

#### Kmeans + centroids

In [ ]:
base = Path("D:/ml/undersampling_data/data/ssh/reduced")
base2 = Path("D:/ml/undersampling_data/models/kmeans&centroids")

df_ = {}

for name in data.keys() & compare.keys():
    # Read data from dictionary
    X_train, y_train = data[name]
    compare_df = compare[name]
    
    # Select majority class
    X_majority = X_train[y_train == 1]
    
    # Apply KMeans clustering
    KM = KMeans(n_clusters=(int)(count2))
    kmeans = KM.fit(X_majority)
    
    # Save KMeans model
    file_path2 = base2 / f"{name}_kmeans_model.pkl"
    with open(file_path2, "wb") as f:
        pickle.dump(kmeans, f)
    
    # Create a DataFrame for centroids
    X_majority_reduced = pd.DataFrame(kmeans.cluster_centers_, columns=X_train.columns)
    y_majority_reduced = pd.Series([1] * (int)(count2), name="target") 
    
    # Combine reduced majority class with original minority class
    df_majority = pd.concat([X_majority_reduced, y_majority_reduced], axis=1).reset_index(drop=True)
    
    # Add source column if not present
    df_majority["source"] = None
    missing_source = df_majority[df_majority["source"].isna()]
    if not missing_source.empty:
        df_majority.loc[df_majority["source"].isna(), "source"] = "centroid" 
    
    print(df_majority)
    df_majority = df_majority.reindex(columns=original_df.columns, fill_value=0.0)
    
    # Combine with original minority class
    df_[name] = pd.concat([df_majority, original_df], axis=0).reset_index(drop=True)  
    
    print(df_[name].info())
    
    # Save to CSV if file does not exist
    file_path = base / f"{name}_KM_centroids.csv"

    if os.path.exists(file_path):
        print("File exists.")
    else:
        df_[name].to_csv(file_path, index=False)
        print("File saved.")

In [ ]:
    user_cols = [
    'kamran', 'student', 'root', 'admins', 'phoenix', 'piglet',
    'rainbow', 'runner', 'sam', 'abc123', 'passwd', 'newpass',
    'notused', 'Hockey', 'internet', 'asshole', 'Maddock', 'computer',
    'Mickey', 'qwerty', 'fiction', 'orange', 'tigger', 'wheeling',
    'mustang', 'admin', 'jennifer', 'money', 'Justin', 'chris',
    'david', 'foobar', 'buster', 'harley', 'jordan', 'stupid',
    'apple', 'fred', 'summer', 'sunshine', 'andrew', 'osamac',
    'gta', 'adminx', 'gtta', 'osamax'
    ]
    df = df_[name]
    # policz sumę wartości 1 w każdym wierszu
    row_sums = df[user_cols].sum(axis=1)
    mask = row_sums == 1

    # jeśli chcesz sprawdzić globalnie:
    all_ok = mask.all()

    print("Czy każdy wiersz ma dokładnie jedno '1' w kolumnach 1–45? ->", all_ok)

### KMeans + The Nearest Neighbor

In [ ]:
base = Path("D:/ml/undersampling_data/data/ssh/reduced")
base2 = Path("D:/ml/undersampling_data/models/kmeans&nn")

cluster_data_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}
centroids_ = {}

results_ = {}
df_ = {}

results_KM_NN_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}


for name in data.keys() & compare.keys():
    # Read data from dictionary
    X_train, y_train = data[name]
    compare_df = compare[name]
    
    # Select majority class (synthetic samples)
    X_majority = X_train[y_train == 1]
    
    # Apply KMeans clustering
    KM = KMeans(n_clusters=(int)(count2))
    kmeans = KM.fit(X_majority)
    
    # Save KMeans model
    file_path2 = base2 / f"{name}_kmeans_model.pkl"
    with open(file_path2, "wb") as f:
        pickle.dump(kmeans, f)
    
    # Centroids + Add rows to dictionary
    for i in range ((int)(count2)):
        rows_in_cluster = X_majority[kmeans.labels_ == i] 
        cluster_data_[name][i] = rows_in_cluster
        
        centroids_ = pd.DataFrame(kmeans.cluster_centers_, columns=X_train.columns)
    
    # Original minority class
    for i in range(len(centroids_)):
        if (len(cluster_data_[name][i])>1):     # If more than one sample in the cluster
            dist_={}
            index_ = {}
            centroid = centroids_.iloc[i]
            for j in range(len(cluster_data_[name][i])):
                index_ = list(cluster_data_[name][i].index)
                row = cluster_data_[name][i].iloc[j]
                index_map = {j: idx for j, idx in enumerate(index_)}
                dist_[j] = euclidean(centroid, row)         # Colculate Euclidean distance
                
            min_key = min(dist_, key=dist_.get)
            results_KM_NN_[name][i] = cluster_data_[name][i].iloc[[min_key]]    # Select the nearest neighbor to the centroid
            
        else:           # If only one sample in the cluster
            results_KM_NN_[name][i] = cluster_data_[name][i].iloc[[0]]
        
        results_[name] = pd.concat(results_KM_NN_[name].values(), ignore_index=True)    
    
    # Combine reduced majority class with original df
    df_y_majority = pd.Series([1] * (int)(count2), name="target") 
    df_majority = pd.concat([results_[name], df_y_majority], axis=1).reset_index(drop=True)
    columns_ = list(df_majority.columns.values)
    df_majority = df_majority.merge(sum_all_data, on=columns_, how="left")
     
    df_[name] = pd.concat([df_majority, original_df], axis=0).reset_index(drop=True) 
    
    print(df_[name].info())
    
    # Save to CSV if file does not exist
    file_path = base / f"{name}_KM_nn.csv"

    if os.path.exists(file_path):
        print("File exists.")
    else:
        df_[name].to_csv(file_path, index=False)
        print("File saved.")

### KMeans + cosinus similarity

In [9]:
base = Path("D:/ml/undersampling_data/data/ssh/reduced")
base2 = Path("D:/ml/undersampling_data/models/kmeans&cos")

cluster_data_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}
centroids_ = {}

results_ = {}
df_ = {}

results_KM_COS_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}


for name in data.keys() & compare.keys():
    # Read data from dictionary
    X_train, y_train = data[name]
    compare_df = compare[name]
    
    # Select majority class (synthetic samples)
    X_majority = X_train[y_train == 1]
    
    # Apply KMeans clustering
    KM = KMeans(n_clusters=(int)(count2))
    kmeans = KM.fit(X_majority)
    
    # Save KMeans model
    file_path2 = base2 / f"{name}_kmeans_model.pkl"
    with open(file_path2, "wb") as f:
        pickle.dump(kmeans, f)
    
    # Centroids + Add rows to dictionary
    for i in range ((int)(count2)):
        rows_in_cluster = X_majority[kmeans.labels_ == i] 
        cluster_data_[name][i] = rows_in_cluster
        
        centroids_ = pd.DataFrame(kmeans.cluster_centers_, columns=X_train.columns)
    
    # Original majority class
    for i in range(len(centroids_)):                
        if (len(cluster_data_[name][i])>1):       # If more than one sample in the cluster
            dist_ = {}
            index_ = {}
            centroid = centroids_.iloc[i]
            centroid = centroid.values.reshape(1,-1)
            for j in range(len(cluster_data_[name][i])):
                index_ = list(cluster_data_[name][i].index)
                row = cluster_data_[name][i].iloc[j]
                row = row.values.reshape(1,-1)
                index_map = {j: idx for j, idx in enumerate(index_)}
                dist_[j] = cosine_similarity(centroid, row)         # Colculate Cosine similarity
                
            min_key = max(dist_, key=dist_.get)
            results_KM_COS_[name][i] = cluster_data_[name][i].iloc[[min_key]]   # Select the nearest neighbor to the centroid
            
        else:       # If only one sample in the cluster
            results_KM_COS_[name][i] = cluster_data_[name][i].iloc[[0]]
        
        results_[name] = pd.concat(results_KM_COS_[name].values(), ignore_index=True)       
    
    # Combine reduced majority class with original df
    df_y_majority = pd.Series([1] * (int)(count2), name="target") 
    df_majority = pd.concat([results_[name], df_y_majority], axis=1).reset_index(drop=True)
    columns_ = list(df_majority.columns.values)
    df_majority = df_majority.merge(sum_all_data, on=columns_, how="left")
     
    df_[name] = pd.concat([df_majority, original_df], axis=0).reset_index(drop=True) 
    
    print(df_[name].info())
    
    # Save to CSV if file does not exist
    file_path = base / f"{name}_KM_cos.csv"

    if os.path.exists(file_path):
        print("File exists.")
    else:
        df_[name].to_csv(file_path, index=False)
        print("File saved.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.

### KMeans + cos + Mahalanobis distance

In [14]:
base = Path("D:/ml/undersampling_data/data/ssh/reduced")
base2 = Path("D:/ml/undersampling_data/models/kmeans&cos&mal")

cluster_data_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}
centroids_ = {}

results_ = {}
df_ = {}

results_KM_COS_MAN_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}

alfa = 0.5  #wazenie

for name in data.keys() & compare.keys():
    # Read data from dictionary
    X_train, y_train = data[name]
    compare_df = compare[name]
    
    # Select majority class (synthetic samples)
    X_majority = X_train[y_train == 1]
        
    # Apply KMeans clustering
    KM = KMeans(n_clusters=(int)(count2))
    kmeans = KM.fit(X_majority)
    
    # Save KMeans model
    file_path2 = base2 / f"{name}_kmeans_model.pkl"
    with open(file_path2, "wb") as f:
        pickle.dump(kmeans, f)
    
    # Centroids + Add rows to dictionary
    for i in range ((int)(count2)):
        rows_in_cluster = X_majority[kmeans.labels_ == i] 
        cluster_data_[name][i] = rows_in_cluster
        
        centroids_ = pd.DataFrame(kmeans.cluster_centers_, columns=X_train.columns)
    
    # Original majority class
    for i in range(len(centroids_)):               
        if (len(cluster_data_[name][i])>1):       # If more than one sample in the cluster
            cos_={}
            dist_={}
            comb_score_ = {} # results for cosine similarity and Mahalanobis distance
            index_ = {}
            centroid = centroids_.iloc[i]
            centroid = centroid.values.reshape(1,-1)
            for j in range(len(cluster_data_[name][i])):
                index_ = list(cluster_data_[name][i].index)
                row = cluster_data_[name][i].iloc[j]
                row = row.values.reshape(1,-1)
                index_map = {j: idx for j, idx in enumerate(index_)}
                cos_[j] = cosine_similarity(centroid, row)[0,0]          # using Cosine similarity
                dist_[j] = distance.mahalanobis(centroid.flatten(), row.flatten(), np.linalg.pinv(np.cov(X_train.T)))  # using Mahalanobis distance
                
                comb_score_[j] = (alfa*cos_[j] + (1-alfa)*dist_[j])
                
            min_key = min(comb_score_, key=comb_score_.get)
            results_KM_COS_[name][i] = cluster_data_[name][i].iloc[[min_key]]
            
        else:
            results_KM_COS_[name][i] = cluster_data_[name][i].iloc[[0]]
        
        results_[name] = pd.concat(results_KM_COS_[name].values(), ignore_index=True)   
    
    # Combine reduced majority class with original df
    df_y_majority = pd.Series([1] * (int)(count2), name="target") 
    df_majority = pd.concat([results_[name], df_y_majority], axis=1).reset_index(drop=True)
    columns_ = list(df_majority.columns.values)
    df_majority = df_majority.merge(sum_all_data, on=columns_, how="left")
     
    df_[name] = pd.concat([df_majority, original_df], axis=0).reset_index(drop=True) 
    
    print(df_[name].info())
    
    # Save to CSV if file does not exist
    file_path = base / f"{name}_KM_cos_mal.csv"

    if os.path.exists(file_path):
        print("File exists.")
    else:
        df_[name].to_csv(file_path, index=False)
        print("File saved.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File exists.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File exists.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           303 non-null    float64
 1   student          303 non-null    float64
 2   root             303 non-null    float64
 3   admins           303 non-null    float64
 4   phoenix          303 non-null    float64
 5   piglet           303 non-null    float64
 6   rainbow          303 non-null    float64
 7   runner           303 non-null    float64
 8   sam              303 non-null    float64
 9   abc123           303 non-null    float64
 10  passwd           303 non-null    float64
 11  newpass          303 non-null    float64
 12  notused          303 non-null    float64
 13  Hockey           303 non-null    float64
 14  internet         303 non-null    float64
 15  asshole          303 non-null    float64
 16  Maddock          303 non-null    float64
 17  computer         303 non-null    float64
 18  Mickey           303 non-null    float64
 19  qwerty           303 non-null    float64
 20  fiction          303 non-null    float64
 21  orange           303 non-null    float64
 22  tigger           303 non-null    float64
 23  wheeling         303 non-null    float64
 24  mustang          303 non-null    float64
 25  admin            303 non-null    float64
 26  jennifer         303 non-null    float64
 27  money            303 non-null    float64
 28  Justin           303 non-null    float64
 29  chris            303 non-null    float64
 30  david            303 non-null    float64
 31  foobar           303 non-null    float64
 32  buster           303 non-null    float64
 33  harley           303 non-null    float64
 34  jordan           303 non-null    float64
 35  stupid           303 non-null    float64
 36  apple            303 non-null    float64
 37  fred             303 non-null    float64
 38  summer           303 non-null    float64
 39  sunshine         303 non-null    float64
 40  andrew           303 non-null    float64
 41  osamac           303 non-null    float64
 42  gta              303 non-null    float64
 43  adminx           303 non-null    float64
 44  gtta             303 non-null    float64
 45  osamax           303 non-null    float64
 46  is_private       303 non-null    float64
 47  is_failure       303 non-null    float64
 48  is_root          303 non-null    float64
 49  is_valid         303 non-null    float64
 50  not_valid_count  303 non-null    float64
 51  ip_failure       303 non-null    float64
 52  ip_success       303 non-null    float64
 53  no_failure       303 non-null    float64
 54  first            303 non-null    float64
 55  td               303 non-null    float64
 56  ts               303 non-null    float64
 57  target           303 non-null    float64
 58  source           303 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.8+ KB
None
File exists.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           303 non-null    float64
 1   student          303 non-null    float64
 2   root             303 non-null    float64
 3   admins           303 non-null    float64
 4   phoenix          303 non-null    float64
 5   piglet           303 non-null    float64
 6   rainbow          303 non-null    float64
 7   runner           303 non-null    float64
 8   sam              303 non-null    float64
 9   abc123           303 non-null    float64
 10  passwd           303 non-null    float64
 11  newpass          303 non-null    float64
 12  notused          303 non-null    float64
 13  Hockey           303 non-null    float64
 14  internet         303 non-null    float64
 15  asshole          303 non-null    float64
 16  Maddock          303 non-null    float64
 17  computer         303 non-null    float64
 18  Mickey           303 non-null    float64
 19  qwerty           303 non-null    float64
 20  fiction          303 non-null    float64
 21  orange           303 non-null    float64
 22  tigger           303 non-null    float64
 23  wheeling         303 non-null    float64
 24  mustang          303 non-null    float64
 25  admin            303 non-null    float64
 26  jennifer         303 non-null    float64
 27  money            303 non-null    float64
 28  Justin           303 non-null    float64
 29  chris            303 non-null    float64
 30  david            303 non-null    float64
 31  foobar           303 non-null    float64
 32  buster           303 non-null    float64
 33  harley           303 non-null    float64
 34  jordan           303 non-null    float64
 35  stupid           303 non-null    float64
 36  apple            303 non-null    float64
 37  fred             303 non-null    float64
 38  summer           303 non-null    float64
 39  sunshine         303 non-null    float64
 40  andrew           303 non-null    float64
 41  osamac           303 non-null    float64
 42  gta              303 non-null    float64
 43  adminx           303 non-null    float64
 44  gtta             303 non-null    float64
 45  osamax           303 non-null    float64
 46  is_private       303 non-null    float64
 47  is_failure       303 non-null    float64
 48  is_root          303 non-null    float64
 49  is_valid         303 non-null    float64
 50  not_valid_count  303 non-null    float64
 51  ip_failure       303 non-null    float64
 52  ip_success       303 non-null    float64
 53  no_failure       303 non-null    float64
 54  first            303 non-null    float64
 55  td               303 non-null    float64
 56  ts               303 non-null    float64
 57  target           303 non-null    float64
 58  source           303 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.8+ KB
None
File exists.

### HDBSCAN + Euclidean distance

In [ ]:
base = Path("D:/ml/undersampling_data/data/ssh/reduced")
base2 = Path("D:/ml/undersampling_data/models/hdbscan&nn")

cluster_data_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}
centroids_ = {}

results_ = {}
df_ = {}

results_HDBSCAN_DIST_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}
labels_={}

for name in data.keys() & compare.keys():
    # Read data from dictionary
    X_train, y_train = data[name]
    compare_df = compare[name]
    
    # Select majority class (synthetic samples)
    X_majority = X_train[y_train == 1]
    
    # Apply HDBSCAN clustering
    hdbscan = HDBSCAN(store_centers="centroid")
    hdbscan_res = hdbscan.fit(X_majority)
    
    # Save HDBSCAN model
    file_path2 = base2 / f"{name}_hdbscan_model.pkl"
    with open(file_path2, "wb") as f:
        pickle.dump(hdbscan, f)
    
    # Get labels and number of clusters
    labels = hdbscan_res.labels_
    unique_lables = np.unique(labels)
    labels_[name] = len(unique_lables[unique_lables >=0])
    labels = len(unique_lables[unique_lables >=0])
    print(f"{name}: {labels_[name]}")
    
    # Centroids from HDBSCAN
    centroids_ = pd.DataFrame(hdbscan_res.centroids_, columns=X_train.columns)
    centroids_hdbscan = hdbscan.fit_predict(X_majority)

    # Add rows to cluster dictionary
    for i in range(labels):
        rows_in_cluster = X_majority[hdbscan.labels_ == i] 
        cluster_data_[name][i] = rows_in_cluster

        target = count2
        
        # Sorted neighbors dictionary
        per_cluster_sorted = {}
        
        # Calculate the nieghbors for each centroid (centroid -> rows_in_cluster)
    for i in range(len(centroids_)):
        rows = cluster_data_[name][i]
        if len(rows) == 0:
            per_cluster_sorted[i] = []
            continue
        if len(rows) == 1:
            per_cluster_sorted[i] = [rows.index[0]]
            continue

        centroid = centroids_.iloc[i].to_numpy()
        # Calculate Euclidean distances from centroid to all points in the cluster
        dists = rows.apply(lambda r: euclidean(centroid, r.to_numpy()), axis=1)
        order = dists.sort_values().index.tolist()  # indeksy X_majority w kolejności rosnących dystansów
        per_cluster_sorted[i] = order

    # Round-robin chooice to target_n
    selected_idx = []
    ptr = {i: 0 for i in range(len(centroids_))}                     # Which "index" to take now from the cluster
    while len(selected_idx) < target:
        progressed = False
        for i in range(len(centroids_)):
            lst = per_cluster_sorted[i]
            j = ptr[i]
            if j < len(lst):
                idx = lst[j]
                if idx not in selected_idx:
                    selected_idx.append(idx)
                ptr[i] += 1
                progressed = True
                if len(selected_idx) >= target:
                    break
        if not progressed:
            break

    # Choose selected records of majority class (in order of selection)
    maj_selected = X_majority.loc[selected_idx].reset_index(drop=True)
    results_[name] = maj_selected   
    
    # Combine reduced majority class with original df    
    df_y_majority = pd.Series([1.0] * len(results_[name]), name="target")
    df_majority = pd.concat([results_[name], df_y_majority], axis=1).reset_index(drop=True)
    columns_ = list(df_majority.columns.values)
    df_majority = df_majority.merge(sum_all_data, on=columns_, how="left")
     
    df_[name] = pd.concat([df_majority, original_df], axis=0).reset_index(drop=True)  
    #print(df_[name])

    print(df_[name].info())

    # Save to CSV if file does not exist
    file_path = base / f"{name}_HDBSCAN_NN.csv"

    if os.path.exists(file_path):
        print("File exists.")
    else:
        df_[name].to_csv(file_path, index=False)
        print("File saved.")

GAN: 2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
mix: 123
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
borderline: 24
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           303 non-null    float64
 1   student          303 non-null    float64
 2   root             303 non-null    float64
 3   admins           303 non-null    float64
 4   phoenix          303 non-null    float64
 5   piglet           303 non-null    float64
 6   rainbow          303 non-null    float64
 7   runner           303 non-null    float64
 8   sam              303 non-null    float64
 9   abc123           303 non-null    float64
 10  passwd           303 non-null    float64
 11  newpass          303 non-null    float64
 12  notused          303 non-null    float64
 13  Hockey           303 non-null    float64
 14  internet         303 non-null    float64
 15  asshole          303 non-null    float64
 16  Maddock          303 non-null    float64
 17  computer         303 non-null    float64
 18  Mickey           303 non-null    float64
 19  qwerty           303 non-null    float64
 20  fiction          303 non-null    float64
 21  orange           303 non-null    float64
 22  tigger           303 non-null    float64
 23  wheeling         303 non-null    float64
 24  mustang          303 non-null    float64
 25  admin            303 non-null    float64
 26  jennifer         303 non-null    float64
 27  money            303 non-null    float64
 28  Justin           303 non-null    float64
 29  chris            303 non-null    float64
 30  david            303 non-null    float64
 31  foobar           303 non-null    float64
 32  buster           303 non-null    float64
 33  harley           303 non-null    float64
 34  jordan           303 non-null    float64
 35  stupid           303 non-null    float64
 36  apple            303 non-null    float64
 37  fred             303 non-null    float64
 38  summer           303 non-null    float64
 39  sunshine         303 non-null    float64
 40  andrew           303 non-null    float64
 41  osamac           303 non-null    float64
 42  gta              303 non-null    float64
 43  adminx           303 non-null    float64
 44  gtta             303 non-null    float64
 45  osamax           303 non-null    float64
 46  is_private       303 non-null    float64
 47  is_failure       303 non-null    float64
 48  is_root          303 non-null    float64
 49  is_valid         303 non-null    float64
 50  not_valid_count  303 non-null    float64
 51  ip_failure       303 non-null    float64
 52  ip_success       303 non-null    float64
 53  no_failure       303 non-null    float64
 54  first            303 non-null    float64
 55  td               303 non-null    float64
 56  ts               303 non-null    float64
 57  target           303 non-null    float64
 58  source           303 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.8+ KB
None
File saved.
smote: 16
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           303 non-null    float64
 1   student          303 non-null    float64
 2   root             303 non-null    float64
 3   admins           303 non-null    float64
 4   phoenix          303 non-null    float64
 5   piglet           303 non-null    float64
 6   rainbow          303 non-null    float64
 7   runner           303 non-null    float64
 8   sam              303 non-null    float64
 9   abc123           303 non-null    float64
 10  passwd           303 non-null    float64
 11  newpass          303 non-null    float64
 12  notused          303 non-null    float64
 13  Hockey           303 non-null    float64
 14  internet         303 non-null    float64
 15  asshole          303 non-null    float64
 16  Maddock          303 non-null    float64
 17  computer         303 non-null    float64
 18  Mickey           303 non-null    float64
 19  qwerty           303 non-null    float64
 20  fiction          303 non-null    float64
 21  orange           303 non-null    float64
 22  tigger           303 non-null    float64
 23  wheeling         303 non-null    float64
 24  mustang          303 non-null    float64
 25  admin            303 non-null    float64
 26  jennifer         303 non-null    float64
 27  money            303 non-null    float64
 28  Justin           303 non-null    float64
 29  chris            303 non-null    float64
 30  david            303 non-null    float64
 31  foobar           303 non-null    float64
 32  buster           303 non-null    float64
 33  harley           303 non-null    float64
 34  jordan           303 non-null    float64
 35  stupid           303 non-null    float64
 36  apple            303 non-null    float64
 37  fred             303 non-null    float64
 38  summer           303 non-null    float64
 39  sunshine         303 non-null    float64
 40  andrew           303 non-null    float64
 41  osamac           303 non-null    float64
 42  gta              303 non-null    float64
 43  adminx           303 non-null    float64
 44  gtta             303 non-null    float64
 45  osamax           303 non-null    float64
 46  is_private       303 non-null    float64
 47  is_failure       303 non-null    float64
 48  is_root          303 non-null    float64
 49  is_valid         303 non-null    float64
 50  not_valid_count  303 non-null    float64
 51  ip_failure       303 non-null    float64
 52  ip_success       303 non-null    float64
 53  no_failure       303 non-null    float64
 54  first            303 non-null    float64
 55  td               303 non-null    float64
 56  ts               303 non-null    float64
 57  target           303 non-null    float64
 58  source           303 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.8+ KB
None
File saved.

### HDBSCAN + cos

In [15]:
base = Path("D:/ml/undersampling_data/data/ssh/reduced")
base2 = Path("D:/ml/undersampling_data/models/hdbscan&cos")

cluster_data_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}
centroids_ = {}

results_ = {}
df_ = {}

results_HDBSCAN_COS_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}


for name in data.keys() & compare.keys():
    # Read data from dictionary
    X_train, y_train = data[name]
    compare_df = compare[name]
    
    # Select majority class (synthetic samples)
    X_majority = X_train[y_train == 1]
    
    # Apply HDBSCAN clustering
    hdbscan = HDBSCAN(store_centers="centroid")
    hdbscan_res = hdbscan.fit(X_majority)
    
    # Save HDBSCAN model
    file_path2 = base2 / f"{name}_hdbscan_model.pkl"
    with open(file_path2, "wb") as f:
        pickle.dump(hdbscan, f)
        
    # Get labels and number of clusters
    labels = hdbscan_res.labels_
    unique_lables = np.unique(labels)
    labels = len(unique_lables[unique_lables >=0])
    centroids_ = pd.DataFrame(hdbscan_res.centroids_, columns=X_train.columns)
    
    centroids_hdbscan = hdbscan.fit_predict(X_majority)

    # Centroids from HDBSCAN + Add rows to cluster dictionary
    for i in range(labels):
        # Add rows to cluster dictionary
        rows_in_cluster = X_majority[hdbscan.labels_ == i] 
        cluster_data_[name][i] = rows_in_cluster
        
        target = count2

        # Sorted crucial indexes from clusters
        per_cluster_sorted = {}
        
        # Calculate the nieghbors for each centroid (centroid -> rows_in_cluster)
    for i in range(len(centroids_)):
        rows = cluster_data_[name][i]
        if len(rows) == 0:
            per_cluster_sorted[i] = []
            continue
        if len(rows) == 1:
            per_cluster_sorted[i] = [rows.index[0]]
            continue

        centroid = centroids_.iloc[i].to_numpy().reshape(1, -1)
        # Calculate Cosine distances from centroid to all points in the cluster
        dists = pairwise_distances(rows.values, centroid, metric="cosine").ravel()
        order = rows.index[np.argsort(dists)].tolist()  # indeksy X_majority w kolejności rosnących dystansów
        per_cluster_sorted[i] = order

    # Round-robin chooice to target_n
    selected_idx = []
    ptr = {i: 0 for i in range(len(centroids_))}                 # which "index" to take now from the cluster
    while len(selected_idx) < target:
        progressed = False
        for i in range(len(centroids_)):
            lst = per_cluster_sorted[i]
            j = ptr[i]
            if j < len(lst):
                idx = lst[j]
                if idx not in selected_idx:
                    selected_idx.append(idx)
                ptr[i] += 1
                progressed = True
                if len(selected_idx) >= target:
                    break
        if not progressed: 
            break

    # Choose selected records of majority class (in order of selection)
    maj_selected = X_majority.loc[selected_idx].reset_index(drop=True)
    results_[name] = maj_selected   
    
    # Combine reduced majority class with original df
    df_y_majority = pd.Series([1.0] * len(results_[name]), name="target")
    df_majority = pd.concat([results_[name], df_y_majority], axis=1).reset_index(drop=True)
    columns_ = list(df_majority.columns.values)
    df_majority = df_majority.merge(sum_all_data, on=columns_, how="left")
        
    df_[name] = pd.concat([df_majority, original_df], axis=0).reset_index(drop=True)
    
    print(df_[name].info())
    
    # Save to CSV if file does not exist
    file_path = base / f"{name}_HDBSCAN_cos.csv"

    if os.path.exists(file_path):
        print("File exists.")
    else:
        df_[name].to_csv(file_path, index=False)
        print("File saved.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           303 non-null    float64
 1   student          303 non-null    float64
 2   root             303 non-null    float64
 3   admins           303 non-null    float64
 4   phoenix          303 non-null    float64
 5   piglet           303 non-null    float64
 6   rainbow          303 non-null    float64
 7   runner           303 non-null    float64
 8   sam              303 non-null    float64
 9   abc123           303 non-null    float64
 10  passwd           303 non-null    float64
 11  newpass          303 non-null    float64
 12  notused          303 non-null    float64
 13  Hockey           303 non-null    float64
 14  internet         303 non-null    float64
 15  asshole          303 non-null    float64
 16  Maddock          303 non-null    float64
 17  computer         303 non-null    float64
 18  Mickey           303 non-null    float64
 19  qwerty           303 non-null    float64
 20  fiction          303 non-null    float64
 21  orange           303 non-null    float64
 22  tigger           303 non-null    float64
 23  wheeling         303 non-null    float64
 24  mustang          303 non-null    float64
 25  admin            303 non-null    float64
 26  jennifer         303 non-null    float64
 27  money            303 non-null    float64
 28  Justin           303 non-null    float64
 29  chris            303 non-null    float64
 30  david            303 non-null    float64
 31  foobar           303 non-null    float64
 32  buster           303 non-null    float64
 33  harley           303 non-null    float64
 34  jordan           303 non-null    float64
 35  stupid           303 non-null    float64
 36  apple            303 non-null    float64
 37  fred             303 non-null    float64
 38  summer           303 non-null    float64
 39  sunshine         303 non-null    float64
 40  andrew           303 non-null    float64
 41  osamac           303 non-null    float64
 42  gta              303 non-null    float64
 43  adminx           303 non-null    float64
 44  gtta             303 non-null    float64
 45  osamax           303 non-null    float64
 46  is_private       303 non-null    float64
 47  is_failure       303 non-null    float64
 48  is_root          303 non-null    float64
 49  is_valid         303 non-null    float64
 50  not_valid_count  303 non-null    float64
 51  ip_failure       303 non-null    float64
 52  ip_success       303 non-null    float64
 53  no_failure       303 non-null    float64
 54  first            303 non-null    float64
 55  td               303 non-null    float64
 56  ts               303 non-null    float64
 57  target           303 non-null    float64
 58  source           303 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.8+ KB
None
File saved.

### KMeans (samples=HDBSCAN()) + NN

In [ ]:
base = Path("D:/ml/undersampling_data/data/ssh/reduced")
base2 = Path("D:/ml/undersampling_data/models/kmeans&hdbscan&nn")

cluster_data_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}
centroids_ = {}

results_ = {}
df_ = {}

results_KMEANS_HDBSCAN_DIST_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}

for name in data.keys() & compare.keys():
    # Read data from dictionary
    X_train, y_train = data[name]
    compare_df = compare[name]
    
    # Select majority class (synthetic samples)
    X_majority = X_train[y_train == 1]
    
    # Apply KMeans clustering
    KM = KMeans(n_clusters=labels_[name])
    kmeans = KM.fit(X_majority)
    
    # Save KMeans model
    file_path2 = base2 / f"{name}_kmeans_model.pkl"
    with open(file_path2, "wb") as f:
        pickle.dump(kmeans, f)
        
    # Centroids from KMeans + Add rows to cluster dictionary
    for i in range (labels_[name]):
        # Add rows to cluster dictionary
        rows_in_cluster = X_majority[kmeans.labels_ == i] 
        cluster_data_[name][i] = rows_in_cluster
        
        centroids_ = pd.DataFrame(kmeans.cluster_centers_, columns=X_train.columns)
    
    target = count2
    
    # Sorted crucial indexes from clusters
    per_cluster_sorted = {}
    for i in range(len(centroids_)):
        rows = cluster_data_[name][i]
        if len(rows) == 0:
            per_cluster_sorted[i] = []
            continue
        if len(rows) == 1:
            per_cluster_sorted[i] = [rows.index[0]]
            continue
             
        centroid = centroids_.iloc[i].to_numpy()
        # Calculate Euclidean distances from centroid to all points in the cluster
        dists = rows.apply(lambda r: euclidean(centroid, r.to_numpy()), axis=1)
        order = dists.sort_values().index.tolist()  # indexes of X_majority in ascending order of distances
        per_cluster_sorted[i] = order
        
    selected_idx = []
    ptr = {i: 0 for i in range(len(centroids_))}                     # which "index" to take now from the cluster
    while len(selected_idx) < target:
        progressed = False
        for i in range(len(centroids_)):
            lst = per_cluster_sorted[i]
            j = ptr[i]
            if j < len(lst):
                idx = lst[j]
                if idx not in selected_idx:
                    selected_idx.append(idx)
                ptr[i] += 1
                progressed = True
                if len(selected_idx) >= target:
                    break
        if not progressed: 
            break
    
    # Choose selected records of majority class (in order of selection)   
    maj_selected = X_majority.loc[selected_idx].reset_index(drop=True)   
    results_[name] = maj_selected     
    
    # Combine reduced majority class with original df
    df_y_majority = pd.Series([1.0] * len(results_[name]), name="target")
    df_majority = pd.concat([results_[name], df_y_majority], axis=1).reset_index(drop=True)
    columns_ = list(df_majority.columns.values)
    df_majority = df_majority.merge(sum_all_data, on=columns_, how="left")
        
    df_[name] = pd.concat([df_majority, original_df], axis=0).reset_index(drop=True) 
    
    print(df_[name].info()) 
    
    # Save to CSV if file does not exist
    file_path = base / f"{name}_kmeans&hdbscan_nn.csv"

    if os.path.exists(file_path):
        print("File exists.")
    else:
        df_[name].to_csv(file_path, index=False)
        print("File saved.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File exists.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File exists.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File exists.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           303 non-null    float64
 1   student          303 non-null    float64
 2   root             303 non-null    float64
 3   admins           303 non-null    float64
 4   phoenix          303 non-null    float64
 5   piglet           303 non-null    float64
 6   rainbow          303 non-null    float64
 7   runner           303 non-null    float64
 8   sam              303 non-null    float64
 9   abc123           303 non-null    float64
 10  passwd           303 non-null    float64
 11  newpass          303 non-null    float64
 12  notused          303 non-null    float64
 13  Hockey           303 non-null    float64
 14  internet         303 non-null    float64
 15  asshole          303 non-null    float64
 16  Maddock          303 non-null    float64
 17  computer         303 non-null    float64
 18  Mickey           303 non-null    float64
 19  qwerty           303 non-null    float64
 20  fiction          303 non-null    float64
 21  orange           303 non-null    float64
 22  tigger           303 non-null    float64
 23  wheeling         303 non-null    float64
 24  mustang          303 non-null    float64
 25  admin            303 non-null    float64
 26  jennifer         303 non-null    float64
 27  money            303 non-null    float64
 28  Justin           303 non-null    float64
 29  chris            303 non-null    float64
 30  david            303 non-null    float64
 31  foobar           303 non-null    float64
 32  buster           303 non-null    float64
 33  harley           303 non-null    float64
 34  jordan           303 non-null    float64
 35  stupid           303 non-null    float64
 36  apple            303 non-null    float64
 37  fred             303 non-null    float64
 38  summer           303 non-null    float64
 39  sunshine         303 non-null    float64
 40  andrew           303 non-null    float64
 41  osamac           303 non-null    float64
 42  gta              303 non-null    float64
 43  adminx           303 non-null    float64
 44  gtta             303 non-null    float64
 45  osamax           303 non-null    float64
 46  is_private       303 non-null    float64
 47  is_failure       303 non-null    float64
 48  is_root          303 non-null    float64
 49  is_valid         303 non-null    float64
 50  not_valid_count  303 non-null    float64
 51  ip_failure       303 non-null    float64
 52  ip_success       303 non-null    float64
 53  no_failure       303 non-null    float64
 54  first            303 non-null    float64
 55  td               303 non-null    float64
 56  ts               303 non-null    float64
 57  target           303 non-null    float64
 58  source           303 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.8+ KB
None
File exists.

### KMeans (samples=HDBSCAN()) + cosinus

In [21]:
base = Path("D:/ml/undersampling_data/data/ssh/reduced")
base2 = Path("D:/ml/undersampling_data/models/kmeans&hdbscan&cos")

cluster_data_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}
centroids_ = {}

results_ = {}
df_ = {}

results_KMEANS_HDBSCAN_DIST_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}

for name in data.keys() & compare.keys():
    # Read data from dictionary
    X_train, y_train = data[name]
    compare_df = compare[name]
    
    # Select majority class (synthetic samples) 
    X_majority = X_train[y_train == 1]
    
    # Apply KMeans clustering
    KM = KMeans(n_clusters=labels_[name])
    kmeans = KM.fit(X_majority)
    
    # Save KMeans model
    file_path2 = base2 / f"{name}_kmeans_model.pkl"
    with open(file_path2, "wb") as f:
        pickle.dump(kmeans, f)
    
    # Centroids from KMeans + Add rows to cluster dictionary
    for i in range (labels_[name]):
        rows_in_cluster = X_majority[kmeans.labels_ == i] 
        cluster_data_[name][i] = rows_in_cluster
        
        centroids_ = pd.DataFrame(kmeans.cluster_centers_, columns=X_train.columns)
    
    target = count2
    
    # Sorted crucial indexes from clusters
    per_cluster_sorted = {}
    for i in range(len(centroids_)):
        rows = cluster_data_[name][i]
        if len(rows) == 0:
            per_cluster_sorted[i] = []
            continue
        if len(rows) == 1:
            per_cluster_sorted[i] = [rows.index[0]]
            continue
             
        centroid = centroids_.iloc[i].to_numpy().reshape(1, -1)
        # Calculate Cosine distances from centroid to all points in the cluster
        dists = pairwise_distances(rows.values, centroid, metric="cosine").ravel()
        order = rows.index[np.argsort(dists)].tolist()              # indexes of X_majority in ascending order of distances
        per_cluster_sorted[i] = order
        
    selected_idx = []
    ptr = {i: 0 for i in range(len(centroids_))}                     # which "index" to take now from the cluster
    while len(selected_idx) < target:
        progressed = False
        for i in range(len(centroids_)):
            lst = per_cluster_sorted[i]
            j = ptr[i]
            if j < len(lst):
                idx = lst[j]
                if idx not in selected_idx:
                    selected_idx.append(idx)
                ptr[i] += 1
                progressed = True
                if len(selected_idx) >= target:
                    break
        if not progressed:  # wszystkie klastry wyczerpane
            break
        
    # Select selected records of majority class (in order of selection)    
    maj_selected = X_majority.loc[selected_idx].reset_index(drop=True)   # <-- CHANGED
    results_[name] = maj_selected     
    
    # Combine reduced majority class with original df
    df_y_majority = pd.Series([1.0] * len(results_[name]), name="target")
    df_majority = pd.concat([results_[name], df_y_majority], axis=1).reset_index(drop=True)
    columns_ = list(df_majority.columns.values)
    df_majority = df_majority.merge(sum_all_data, on=columns_, how="left")
    
    df_[name] = pd.concat([df_majority, original_df], axis=0).reset_index(drop=True) 
    print(df_[name].info()) 
    
    # Save to CSV if file does not exist
    file_path = base / f"{name}_kmeans&hdbscan_cos.csv"

    if os.path.exists(file_path):
        print("File exists.")
    else:
        df_[name].to_csv(file_path, index=False)
        print("File saved.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File exists.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File exists.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File exists.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File exists.

### KMeans (samples=HDBSCAN()) + cosinus + Mahalanobis

In [38]:
base = Path("D:/ml/undersampling_data/data/ssh/reduced")
base2 = Path("D:/ml/undersampling_data/models/kmeans&hdbscan&cos&mal")

cluster_data_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}
centroids_ = {}

results_ = {}
df_ = {}

results_KMEANS_HDBSCAN_COS_NN_ = {
    "mix": {},
    "smote": {},
    "GAN": {},
    "borderline": {}
}

alfa = 0.5

for name in data.keys() & compare.keys():
    # Read data from dictionary
    X_train, y_train = data[name]
    compare_df = compare[name]
    
    # Select majority class (synthetic samples)
    X_majority = X_train[y_train == 1]
    
    # Apply KMeans clustering
    KM = KMeans(n_clusters=labels_[name])
    kmeans = KM.fit(X_majority)
    
    # Save KMeans model
    file_path2 = base2 / f"{name}_kmeans_model.pkl"
    with open(file_path2, "wb") as f:
        pickle.dump(kmeans, f)
    
    # Centroids from KMeans + Add rows to cluster dictionary
    for i in range (labels_[name]):
        rows_in_cluster = X_majority[kmeans.labels_ == i] 
        cluster_data_[name][i] = rows_in_cluster
        
        centroids_ = pd.DataFrame(kmeans.cluster_centers_, columns=X_train.columns)
        
    target = count2
    
    # Sorted crucial indexes from clusters
    per_cluster_sorted = {}
    for i in range(len(centroids_)):                # for each centroid
        if (len(cluster_data_[name][i])>1):        # check if more than one sample in the cluster
            cos_={}
            dist_={}
            comb_score_ = {}                # results for cosine similarity and Mahalanobis distance
            index_ = {}
            centroid = centroids_.iloc[i]
            centroid = centroid.values.reshape(1,-1)
            for j in range(len(cluster_data_[name][i])):
                index_ = list(cluster_data_[name][i].index)
                row = cluster_data_[name][i].iloc[j]
                row = row.values.reshape(1,-1)
                index_map = {j: idx for j, idx in enumerate(index_)}
                cos_[j] = cosine_similarity(centroid, row)[0,0]         #using Cosine similarity
                dist_[j] = distance.mahalanobis(centroid.flatten(), row.flatten(), np.linalg.pinv(np.cov(X_train.T)))  #using Mahalanobis distance
                
                comb_score_[j] = (alfa*cos_[j] + (1-alfa)*dist_[j])
                
            min_key = min(comb_score_, key=comb_score_.get)
            results_KMEANS_HDBSCAN_COS_NN_[name][i] = cluster_data_[name][i].iloc[[min_key]]
            
            order = sorted(comb_score_, key=comb_score_.get, reverse=True)
            per_cluster_sorted[i] = [cluster_data_[name][i].index[j] for j in order]
                
        else:
            results_KMEANS_HDBSCAN_COS_NN_[name][i] = cluster_data_[name][i].iloc[[0]]
        
    results_[name] = pd.concat(results_KMEANS_HDBSCAN_COS_NN_[name].values(), ignore_index=True)
    
    # Sorted crucial indexes from clusters
    selected_idx = []
    ptr = {i: 0 for i in range(len(centroids_))}                     # which "index" to take now from the cluster
    while len(selected_idx) < target:
        progressed = False
        for i in range(len(centroids_)):
            lst = per_cluster_sorted.get(i, [])
            j = ptr[i]
            if j < len(lst):
                idx = lst[j]
                if idx not in selected_idx:
                    selected_idx.append(idx)
                ptr[i] += 1
                progressed = True
                if len(selected_idx) >= target:
                    break
        if not progressed:  
            break

    # Choose selected records of majority class (in order of selection)
    maj_selected = X_majority.loc[selected_idx].reset_index(drop=True)
    results_[name] = maj_selected     
    
    # Combine reduced majority class with original df
    df_y_majority = pd.Series([1.0] * len(results_[name]), name="target")
    df_majority = pd.concat([results_[name], df_y_majority], axis=1).reset_index(drop=True)
    columns_ = list(df_majority.columns.values)
    df_majority = df_majority.merge(sum_all_data, on=columns_, how="left")
    
    df_[name] = pd.concat([df_majority, original_df], axis=0).reset_index(drop=True) 
    print(df_[name].info()) 
    
    # Save to CSV if file does not exist
    file_path = base / f"{name}_kmeans&hdbscan_cos&mal.csv"

    if os.path.exists(file_path):
        print("File exists.")
    else:
        df_[name].to_csv(file_path, index=False)
        print("File saved.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kamran           302 non-null    float64
 1   student          302 non-null    float64
 2   root             302 non-null    float64
 3   admins           302 non-null    float64
 4   phoenix          302 non-null    float64
 5   piglet           302 non-null    float64
 6   rainbow          302 non-null    float64
 7   runner           302 non-null    float64
 8   sam              302 non-null    float64
 9   abc123           302 non-null    float64
 10  passwd           302 non-null    float64
 11  newpass          302 non-null    float64
 12  notused          302 non-null    float64
 13  Hockey           302 non-null    float64
 14  internet         302 non-null    float64
 15  asshole          302 non-null    float64
 16  Maddock          302 non-null    float64
 17  computer         302 non-null    float64
 18  Mickey           302 non-null    float64
 19  qwerty           302 non-null    float64
 20  fiction          302 non-null    float64
 21  orange           302 non-null    float64
 22  tigger           302 non-null    float64
 23  wheeling         302 non-null    float64
 24  mustang          302 non-null    float64
 25  admin            302 non-null    float64
 26  jennifer         302 non-null    float64
 27  money            302 non-null    float64
 28  Justin           302 non-null    float64
 29  chris            302 non-null    float64
 30  david            302 non-null    float64
 31  foobar           302 non-null    float64
 32  buster           302 non-null    float64
 33  harley           302 non-null    float64
 34  jordan           302 non-null    float64
 35  stupid           302 non-null    float64
 36  apple            302 non-null    float64
 37  fred             302 non-null    float64
 38  summer           302 non-null    float64
 39  sunshine         302 non-null    float64
 40  andrew           302 non-null    float64
 41  osamac           302 non-null    float64
 42  gta              302 non-null    float64
 43  adminx           302 non-null    float64
 44  gtta             302 non-null    float64
 45  osamax           302 non-null    float64
 46  is_private       302 non-null    float64
 47  is_failure       302 non-null    float64
 48  is_root          302 non-null    float64
 49  is_valid         302 non-null    float64
 50  not_valid_count  302 non-null    float64
 51  ip_failure       302 non-null    float64
 52  ip_success       302 non-null    float64
 53  no_failure       302 non-null    float64
 54  first            302 non-null    float64
 55  td               302 non-null    float64
 56  ts               302 non-null    float64
 57  target           302 non-null    float64
 58  source           302 non-null    object
dtypes: float64(58), object(1)
memory usage: 139.3+ KB
None
File saved.